//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by QrWinMFC.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_QrWinMFC_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_TAB_LOCALCAMERA             130
#define IDD_TAB_REMOTECAMERA            132
#define IDD_TAB_CONTROL_PRODUCT         134
#define IDD_TAB_CONTROL_SYSTEM          136
#define IDD_TAB_FEATURE_CALIB           138
#define IDD_TAB_ROI                     141
#define IDD_TAB_IMAGE                   143
#define IDD_TAB_CALIB                   145
#define IDD_TAB_CAMERA_PREVIEW          147
#define IDD_TAB_VIDEO_PREVIEW           149
#define IDC_TAB_CAMERA                  1000
#define IDC_PICTUREBOX                  1001
#define IDC_COMBO1                      1002
#define IDC_COMBO_LOCAL_CAMERALIST      1002
#define IDC_COMBO_TRSM_GUIDE_TO         1002
#define IDC_COMBO_ROI_LIST              1002
#define IDC_COMBO_COLOR_MAP             1002
#define IDC_COMBO_PROTOCOL              1002
#define IDC_COMBO_VIEW_MODE             1002
#define IDC_COMBO_TEMPUNIT              1002
#define IDC_COMBO2                      1003
#define IDC_COMBO_LOCAL_SERIALPORT      1003
#define IDC_COMBO_IP_MODE               1003
#define IDC_COMBO_CEM                   1003
#define IDC_BUTTON_LOCAL_CONNECT        1004
#define IDC_IPADDRESS1                  1005
#define IDC_IPADDRESS                   1005
#define IDC_MAC_ADDRESS                 1005
#define IDC_BUTTON1                     1006
#define IDC_BUTTON_REMOTE_CONNECT       1006
#define IDC_BUTTON_GET_PRODUCT_INFO     1006
#define IDC_IP_ADDRESS                  1006
#define IDC_BUTTON_CLEAR_ROI            1006
#define IDC_BUTTON_OPEN_CALIB           1006
#define IDC_BUTTON_VIDEO_FILE_RECORD    1006
#define IDC_BUTTON_BEGIN_ACQUISITION    1006
#define IDC_TAB_CONTROL                 1007
#define IDC_BUTTON_GET_VERSION_INFO     1007
#define IDC_GATEWAY_ADDRESS             1007
#define IDC_BUTTON_UPDATE_PARAMS        1007
#define IDC_BUTTON_SAVE_ROI_FRAME       1007
#define IDC_BUTTON_VIDEO_RECORD         1007
#define IDC_BUTTON_BEGIN_ACQUISITION2   1007
#define IDC_BUTTON_END_ACQUISITION      1007
#define IDC_TAB_FEATURE                 1008
#define IDC_SUBNETMASK                  1008
#define IDC_BUTTON_SAVE_ROI_IMAGE       1008
#define IDC_BUTTON_VIDEO_FILE_OPEN      1008
#define IDC_DNS_ADDRESS                 1009
#define IDC_BUTTON_VIDEO_PLAY           1009
#define IDC_BUTTON_GET_MODEL            1010
#define IDC_BUTTON_SET_LINEAR           1010
#define IDC_EDIT_MODEL                  1011
#define IDC_EDIT_PRODUCT_VERSION        1012
#define IDC_EDIT_HW_VERSION             1013
#define IDC_EDIT_SW_VERSION             1014
#define IDC_EDIT_BUILD_DATE             1015
#define IDC_EDIT_BUILD_TIME             1016
#define IDC_EDIT_PRODUCT_SERIAL         1017
#define IDC_EDIT_SENSOR_SERIAL          1018
#define IDC_BUTTON_GET_PRODUCT_SERIAL   1019
#define IDC_BUTTON_GET_SENSOR_SERIAL    1020
#define IDC_BUTTON_GET_GAIN_MODE        1021
#define IDC_RADIO_GAIN_HIGH             1022
#define IDC_RADIO_GAIN_LOW              1023
#define IDC_BUTTON_SET_GAIN_MODE        1024
#define IDC_EDIT_REF_GAIN               1025
#define IDC_BUTTON_SET_REF_GAIN         1026
#define IDC_EDIT_REF_OFFSET             1027
#define IDC_BUTTON_SET_REF_OFFSET       1028
#define IDC_EDIT_TEMP_COEFF1            1029
#define IDC_BUTTON_SET_TEMP_COEFF1      1030
#define IDC_EDIT_SHUTTER_TIME           1030
#define IDC_EDIT_TEMP_COEFF2            1031
#define IDC_BUTTON_SET_SHUTTER_TIME     1031
#define IDC_BUTTON_SET_TEMP_COEFF2      1032
#define IDC_RADIO_ALARM_NUC_ON          1032
#define IDC_BUTTON_GET_TEMP_INFO        1033
#define IDC_RADIO_ALARM_NUC_OFF         1033
#define IDC_EDIT_TEMP_FPA               1034
#define IDC_BUTTON_SET_ALARM_NUC        1034
#define IDC_EDIT_TEMP_BODY              1035
#define IDC_BUTTON_GET_VERSION          1036
#define IDC_BUTTON_GET_PRODUCT_VERSION  1036
#define IDC_BUTTON_GET_HW_VERSION       1037
#define IDC_BUTTON_GET_SW_VERSION       1038
#define IDC_RADIO_TRSM_COMP_ON          1039
#define IDC_BUTTON_GET_BUILD_DATE       1039
#define IDC_RADIO_AUTOSHUTTER_ON        1039
#define IDC_RADIO_TRSM_COMP_OFF         1040
#define IDC_BUTTON_GET_BUILD_TIME       1040
#define IDC_RADIO_AUTOSHUTTER_OFF       1040
#define IDC_BUTTON_SET_TRSM_COMP        1041
#define IDC_BUTTON_GET_REF_GAIN         1041
#define IDC_RADIO_TRSM_GUIDE_ON         1042
#define IDC_BUTTON_GET_REF_OFFSET       1042
#define IDC_RADIO_TRSM_GUIDE_OFF        1043
#define IDC_BUTTON_GET_TEMP_COEFF1      1043
#define IDC_EDIT_OUT_FORMAT             1044
#define IDC_BUTTON_SET_TRSM_GUIDE       1044
#define IDC_BUTTON_GET_MAC_ADDRESS      1045
#define IDC_BUTTON_GET_TEMP_COEFF2      1045
#define IDC_EDIT_BLACK_WHITE            1046
#define IDC_BUTTON_GET_VIDEO_RESOLUTION 1046
#define IDC_EDIT_BRIGHTNESS             1047
#define IDC_BUTTON_SET_TRSM_VALUE       1047
#define IDC_STR_ROI_X                   1047
#define IDC_EDIT_BOOT_MODE              1048
#define IDC_EDIT_TRSM_VALUE             1048
#define IDC_STR_ROI_Y                   1048
#define IDC_EDIT_DISPLAY_SETTING        1049
#define IDC_BUTTON_SET_TRSM_SAVE        1049
#define IDC_STR_ROI_W                   1049
#define IDC_RADIO_TEMP_PRINT_ON         1050
#define IDC_STR_ROI_H                   1050
#define IDC_BUTTON_GET_BODY_TEMP        1050
#define IDC_BUTTON_SET_TRSM_REF_TEMP    1050
#define IDC_EDIT_CEM                    1051
#define IDC_RADIO_TEMP_PRINT_OFF        1051
#define IDC_BUTTON_ADD_ROI              1051
#define IDC_EDIT_TRSM_REF_TEMP          1051
#define IDC_EDIT_PSEUDO_COLOR           1052
#define IDC_BUTTON_SET_TEMP_PRINT       1052
#define IDC_BUTTON_REMOVE_ROI           1052
#define IDC_EDIT_CONTRAST               1053
#define IDC_EDIT_VIDEO_RESOLUTION       1053
#define IDC_BUTTON_LOAD_FRAME           1053
#define IDC_EDIT_SHUTTER_MODE           1054
#define IDC_BUTTON_GET_IP_MODE          1054
#define IDC_BUTTON_SAVE_FRAME           1054
#define IDC_EDIT_LINEAR_GAIN            1054
#define IDC_EDIT_CAPTURE_SETTING        1055
#define IDC_BUTTON_SET_IP_MODE          1055
#define IDC_BUTTON_SAVE_IMAGE           1055
#define IDC_EDIT_LINEAR_OFFSET          1055
#define IDC_EDIT_OBJ_EMISSIVITY         1055
#define IDC_BUTTON_GET_SYSTEM_INFO      1056
#define IDC_BUTTON_GET_IP_ADDRESS       1056
#define IDC_BUTTON_LOAD_IMAGE           1056
#define IDC_EDIT_REFL_TEMP              1056
#define IDC_TAB_PREVIEW                 1056
#define IDC_BUTTON_CAPTURE              1056
#define IDC_BUTTON_SET_IP_ADDRESS       1057
#define IDC_BUTTON_SAVE_BITMAP          1057
#define IDC_EDIT_DISTANCE               1057
#define IDC_PICTUREBOX_VIDEO            1057
#define IDC_BUTTON_SET_AUTOSHUTTER2     1057
#define IDC_BUTTON_SET_AUTOSHUTTER      1057
#define IDC_BUTTON_GET_GATEWAY_ADDRESS  1058
#define IDC_BUTTON_OPEN_LOG_FILE        1058
#define IDC_EDIT_ATM_TEMP               1058
#define IDC_BUTTON_GET_FPA_TEMP         1058
#define IDC_BUTTON_LOAD_IMAGE2          1058
#define IDC_BUTTON_LOAD_BITMAP          1058
#define IDC_BUTTON_SET_GATEWAY_ADDRESS  1059
#define IDC_BUTTON_LOG_ITEM             1059
#define IDC_EDIT_HUMIDITY               1059
#define IDC_STATIC_VIDEO_INFO           1059
#define IDC_BUTTON_GET_SUBNETMASK       1060
#define IDC_EDIT_ATM_TRANS              1060
#define IDC_STATIC_FILE_VIDEO           1060
#define IDC_BUTTON_GET_WHITE_BLACK_HOT  1060
#define IDC_BUTTON_SET_SUBNETMASK       1061
#define IDC_EDIT_LENS_TEMP              1061
#define IDC_STATIC_FILE_RECORD          1061
#define IDC_RADIO_HOT_WHITE             1061
#define IDC_BUTTON_GET_DNS_ADDRESS      1062
#define IDC_EDIT_LENS_TRANS             1062
#define IDC_RADIO_RECORD_FRAME          1062
#define IDC_RADIO_HOT_BLACK             1062
#define IDC_BUTTON_SET_DNS_ADDRESS      1063
#define IDC_BUTTON_SET_HOT_WHITE_BLACK  1063
#define IDC_EDIT_VIDEO_FPS              1064
#define IDC_RADIO_RECORD_IMAGE          1064
#define IDC_RADIO_AUTOSHUTTER_ON3       1064
#define IDC_RADIO_SHUTTER_              1064
#define IDC_RADIO_SHUTTER_CTRL_OPEN     1064
#define IDC_BUTTON_GET_VIDEO_FPS        1065
#define IDC_PROGRESS1                   1065
#define IDC_PROGRESS_VIDEO_READ         1065
#define IDC_RADIO_AUTOSHUTTER_OFF3      1065
#define IDC_RADIO_SHUTTER_CTRL_CLOSE    1065
#define IDC_EDIT_VIDEO_FORMAT           1066
#define IDC_STATIC_VIDEO_FRAME_POS      1066
#define IDC_BUTTON_SET_AUTOSHUTTER3     1066
#define IDC_BUTTON_SET_SHUTTER_CONTROL  1066
#define IDC_BUTTON_GET_VIDEO_FORMAT     1067
#define IDC_STATIC_VIDEO_TOTAL_FRAMES   1067
#define IDC_BUTTON_SET_SYSTEM_REBOOT    1067
#define IDC_BUTTON_SET_TRSM_VALUE2      1068
#define IDC_BUTTON_SET_TRSM_GUIDE_TO    1068
#define IDC_BUTTON_GET_USECASE          1068
#define IDC_BUTTON_GET_SYSTEM_SETTING   1068
#define IDC_EDIT_USECASE                1069
#define IDC_BUTTON_SET_DNS_ADDRESS2     1069
#define IDC_BUTTON_SET_NETWORK_REBOOT   1069
#define IDC_BUTTON_GET_DISPLAY          1070
#define IDC_BUTTON_GET_PRINTSTATICS     1070
#define IDC_EDIT1                       1070
#define IDC_BUTTON_GET_AUTOSHUTTER2     1070
#define IDC_BUTTON_GET_AUTOSHUTTER      1070
#define IDC_EDIT_ACQUISITION_COUNT      1070
#define IDC_EDIT_DISPLAY                1071
#define IDC_BUTTON_SET_1P_NUC2          1072
#define IDC_BUTTON_SET_1P_NUC           1072
#define IDC_STATIC_RAW_MAX              1072
#define IDC_BUTTON_SET_VIEW_MODE        1073
#define IDC_STATIC_CELSIUS_MAX          1073
#define IDC_STATIC_TEMP_MAX             1073
#define IDC_RADIO_TEC_ON                1074
#define IDC_STATIC_RAW_AVG              1074
#define IDC_RADIO_TEC_OFF               1075
#define IDC_STATIC_TEMP_AVG             1075
#define IDC_RADIO_DPC_ON                1076
#define IDC_STATIC_RAW_MIN              1076
#define IDC_RADIO_DPC_OFF               1077
#define IDC_STATIC_TEMP_MIN             1077
#define IDC_RADIO_2ND_COMP_ON           1078
#define IDC_RADIO_HIGH_GAIN             1078
#define IDC_RADIO_2ND_COMP_OFF          1079
#define IDC_RADIO_HIGH_GAIN2            1079
#define IDC_RADIO_LOW_GAIN              1079
#define IDC_CHECK_CAPTURE_ENABLE        1079
#define IDC_RADIO_SHUTTER_COMP_ON       1080
#define IDC_RADIO_TRIGGERMODE_ON        1080
#define IDC_RADIO_SHUTTER_COMP_OFF      1081
#define IDC_RADIO_TRIGGERMODE_OFF       1081
#define IDC_RADIO_IMAGE_OUT_FIRST       1082
#define IDC_BUTTON_SW_TRIGGER           1082
#define IDC_RADIO_IMAGE_OUT_LAST        1083
#define IDC_RADIO_TEMP_CONVERT_ON       1084
#define IDC_BUTTON_GET_CAMERA_POSITION  1084
#define IDC_RADIO_TEMP_CONVERT_OFF      1085
#define IDC_RADIO_CAMERA_POSITION_LEFT  1085
#define IDC_BUTTON_SET_TEMP_CONVERT2    1086
#define IDC_BUTTON_SET_TEMP_CONVERT     1086
#define IDC_RADIO_CAMERA_POSITION_RIGHT 1086
#define IDC_BUTTON_SET_TEC              1087
#define IDC_BUTTON_SET_CAMERA_POSITION  1087
#define IDC_BUTTON_SET_DPC              1088
#define IDC_RADIO_CAMERA_POSITION_RIGHT2 1088
#define IDC_RADIO_CAMERA_POSITION_UNKNOWN 1088
#define IDC_BUTTON_SET_2ND_COMP         1089
#define IDC_BUTTON_SET_SHUTTER_COMP     1090
#define IDC_BUTTON_SET_IMAGE_OUT        1091

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
